version: '3'
services:
  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
      # - ./data:/app/data
      # - /data/openpredict:/app/data
    # entrypoint: gunicorn -w 8 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8808 --timeout 600 trapi.main:app

    environment:
      # Variable for nginx-proxy routing. See https://github.com/nginx-proxy/
      VIRTUAL_HOST: openpredict.semanticscience.org
      LETSENCRYPT_HOST: openpredict.semanticscience.org
      VIRTUAL_PORT: 8808
      NO_JAEGER: "true"

      # JAEGER_HOST: jaeger-otel-agent.sri
      # JAEGER_PORT: 6831

      # OPENPREDICT_APIKEY: ${OPENPREDICT_APIKEY}

  jaeger-otel-agent.sri:
    image: jaegertracing/all-in-one:latest
    # ports:
    #   - "16686:16686"
    #   - "4318:4318"
    #   - "6831:6831/udp"
    environment:
      LOG_LEVEL: debug
      VIRTUAL_HOST: jaeger.137.120.31.102.nip.io
      LETSENCRYPT_HOST: jaeger.137.120.31.102.nip.io
      VIRTUAL_PORT: 16686