version: "3"

services:

  jupyterlab:
    # container_name: jupyterlab
    image: jupyter/all-spark-notebook
    user: root
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan
    environment:
      - JUPYTER_TOKEN=password
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
